### ISSUE TITLE
Sometimes the vibration does not stop.

### ISSUE THREAD

**Issue by brainbreeze** [dancol90/mi-360#10]
For example in Sekiro: Shadows Die Twice:

When they deal damage to me - the gamepad vibrates.
At this time they kill me and I respawn.
But the vibration continues ...
Up to:
- reboot gamepad or mi360.
- action in the game, causing vibration.

The same in all games.

**Thank you very much :)**

**Comment by brainbreeze** [comment]
**Solution:** use [this controller emulator](https://github.com/irungentoo/Xiaomi_gamepad/releases) ...

**Comment by dancol90** [comment]
Hi, this is related to the way the vibration commands are sent to the device. Being these commands blocking, I have to run them asynchronously to avoid losing user inputs, and there's where the problem lies.

I'll have a look!

**Comment by T3rm1** [comment]
Problem is still there. Fifa 19 for example is unplayable with it. Vibration never stops.
There is another project on Github with SCP Driver which is working fine.

**Comment by zhangbo8418** [comment]
Solution: use https://github.com/grayver/mi-vigem

**Comment by T3rm1** [comment]
> Solution: use https://github.com/grayver/mi-vigem

Thank you for the link. Works perfect.

**Comment by dancol90** [comment]
As stated in https://github.com/grayver/mi-vigem/issues/2, it seems like that this is a ViGEm related issue, as the same happens also in mi-vigem. Thanks @grayver for getting in touch with the ViGEm team and confirming the issue.

I kinda took inspiration (ehm...blatantly copied sounded wrong) and implemented a 3s timeout to vibration in mi-360. It will be available in the next release.

**Comment by dancol90** [comment]
Just released v0.5.2 that fixes this issue: https://github.com/dancol90/mi-360/releases/tag/v0.5.2
