### ISSUE TITLE
Xiaomi gamepad stop working after a few minutes

### ISSUE THREAD

**Issue by FFrelay** [dancol90/mi-360#11]
Not sure it's a Windows 10 (1809) or USB dongle issue (I changed to a Intel 9260) or gamepad itself. The problem is the gamepad works fine at first, but after a few minutes it stop working. The mi button led on the gamepad is still on, the gamepad was not disconnected from the PC, all I need to do is go to Windows Setting > Bluetooth and other devices then magically it works again, then keep stop working a few minutes after that. I must keep switching from game window to "Bluetooth and other devices" window in order to "refesh" it. Please advise, thanks!

**Comment by FFrelay** [comment]
Found similar issue has been discussed here: https://github.com/irungentoo/Xiaomi_gamepad/issues/47

**Comment by sfOoca** [comment]
Same issue systematicaly after a cinematic on assassin's Creed 3 for example

**Comment by dancol90** [comment]
Hi! This seems a Windows 10 issue, maybe related to bluetooth stack. Unfortunately, I've never experienced it yet.

Have you tried with the compatibility mode as suggested in the linked issue?

**Comment by FFrelay** [comment]
Hi, thank for your reply, I did try that suggestion but it did not work.

**Comment by sfOoca** [comment]
I try too, but it doesn't change anything.
It's ok with others apps (but a lot more complicated)

**Comment by FFrelay** [comment]
Windows 1903 build 18362.175 seems to fix this problem.
