### ISSUE TITLE
(v0.5.0) mi-360 has stopped working. The cause of the problem is: Nefarius.ViGEm.Client

### ISSUE THREAD

**Issue by diegoweb** [dancol90/mi-360#17]
I've just received a notification from this repo and I went to update my mi-360.
First I uninstalled v0.4.0 and downloaded Vigem from the [provided link](https://github.com/ViGEm/ViGEmBus/releases). After installing it, I went ahead and installed mi-360 v0.5.0 [from here](https://github.com/dancol90/mi-360/releases/download/v0.5.0/mi-360-v0.5.0-setup.exe).

After executing mi-360 I get this error:
![image](https://user-images.githubusercontent.com/12632119/80042377-32004380-84d5-11ea-935d-0c68895ec71b.png)

_mi-360 has stopped working. The cause of the problem is:
Unable to load file or assembly 'Nefarius.ViGEm.Client, Version=1.16.150.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
System can't find the requested file._

Am I doing something wrong of this latest setup is broken?
Thanks :)

**Comment by dancol90** [comment]
Hi!

I probably forgot something in the installer, sorry for the incoveniance 😅 

Can you try the standalone zip package, please? It should have all the needed dependencies, just extract it anywhere and launch `mi-360.exe`.

**Comment by diegoweb** [comment]
Standalone version works fine :)

**Comment by diegoweb** [comment]
OK, so there're 2 scenarios:

First one:
If I keep everything installed (vigem and mi-360) and extract the standalone version anywhere or even in the mi360 default installation folder, it launches. But doesn't detect the controller.

Second one:
If I uninstall everything, extract the standalone version and try to run mi-360.exe, I get this:
![image](https://user-images.githubusercontent.com/12632119/80151255-1e65e300-8590-11ea-9687-4eadc0689fa3.png)

**Comment by dancol90** [comment]
Yes, that lasst error is expected, as ViGEm is always a requirement, you have to keep it installed

**Comment by dancol90** [comment]
Moving the discussion to #18
