### ISSUE TITLE
mi-360 can not work in Trine3!

### ISSUE THREAD

**Issue by seven1oe** [dancol90/mi-360#2]
At first,I want to thanks for your work!
I found many projects like yours,but they are not work in my controller.
I have ported your code to my controller and it works well expect rumble(By the way,can you tell me how to fix it?).
I tested mi-360 in many games and I found it can not work in Trine3!
Trine3 can recognise the controller is a "Xinput Controller" but the key is not corresponding.
Sorry for my bad English!

**Comment by dancol90** [comment]
Hi!
What do you mean by "ported to my controller"?

**Comment by seven1oe** [comment]
I am sorry for my bad English!  (expect=except)
I modified your code and it works in my controller except rumble.
The keys are corresponding with my gamepad's in many games except Trine3 .It also works in x360ce.
But now, I think this is not your project's problem.
I use VDX(v1.12.1.0) and x360ce, but they can not work in Trine3 as well.

**Comment by dancol90** [comment]
So you are saying that you adapted the code for a different controller, that is not a Xiaomi Gamepad?
If so, the rumble feature is specific for Xiaomi Gamepad: you have to find out how to instruct your device (via HID) to vibrate.

About Trine3, maybe it's a ViGEm bus problem, as you said, and the fact that VDX doesn't work too supports my idea.

Sorry I can't be of more help.

**Comment by seven1oe** [comment]
It doesn't matter.
