### ISSUE TITLE
Duplicate controller?

### ISSUE THREAD

**Issue by Schusti91** [dancol90/mi-360#21]
Hi @dancol90,

I'm glad I found your tool, since my Controller simply won't work with x360ce.

![image](https://user-images.githubusercontent.com/22288752/92166218-8a0e6580-ee38-11ea-9374-cc27db79b0d8.png)

Do you have any idea what could cause this? I see two controllers ingame.
I can't really navigate through the menu, it seems to make commands randomly.

**Comment by dancol90** [comment]
As the latest release note says, Windows 10 does not allow for exclusive mode on HID devices. This means that every application will see the original Xiaomi Gamepad device as long as the emulated Xbox one.

mi-360 will try anyway to obtain exclusive access to the gamepad (that will hide the device to other applications), but if it fails it will revert to the normal, shared access that will leave the device visible to all.

I've tried multiple solutions in the past, but all of them were kinda hack-ish and troublesome. It seems that there is no way to make it in a clean, safe way.
