### ISSUE TITLE
Auto turn off after some rumble.

### ISSUE THREAD

**Issue by DilVika** [dancol90/mi-360#22]
As a title, My gamepad has been turned  off after Vibrate. I thought it because of Battery, but not. I have changed new couple battery, it’s still happend.

Just for more information, Which version of Vigem should I install?

**Comment by dancol90** [comment]
Hi! Usually this problem is indeed related with low-charge batteries. Are you using alkalines or rechargables? Maybe try with a different brand?

For Vigem, I would say just use the latest one (and it should autoupdate once installed, so maybe you already have the latest)

**Comment by DilVika** [comment]
I am using alkalines, maybe I will try rechargable. Thanks for your respon.
