### ISSUE TITLE
Windows update broke everything again.

### ISSUE THREAD

**Issue by XxHansYoloxX** [dancol90/mi-360#23]

**Comment by XxHansYoloxX** [comment]
Exclusivity is broken again, I get 2 controllers instead of xbox controller only. Many games do not work like this, Forza Horizon being one of them. Can this be fixed? 
Thank you for your effort.

**Comment by dancol90** [comment]
Hello! 
I'm working on integrating the new [HidHide](https://github.com/ViGEm/HidHide) driver, that will allow to hide the Xiaomi Controller when it is used by mi-360, even if Windows doesn't let open it in exclusive mode.

Stay tuned for the next release!

**Comment by heeroyuyj** [comment]
> Exclusivity is broken again, I get 2 controllers instead of xbox controller only. Many games do not work like this, Forza Horizon being one of them. Can this be fixed? Thank you for your effort.

same issue here, :(

**Comment by nikolatesluh** [comment]
same

> Exclusivity is broken again, I get 2 controllers instead of xbox controller only. Many games do not work like this, Forza Horizon being one of them. Can this be fixed? Thank you for your effort.

Same, FH5 is just broken.


Thank You @dancol90 I have this gamepad for a while, just dusted it off for forza. Thank you for the tool and the support!

**Comment by dancol90** [comment]
Hi everybody, the new solution with HidHide seems to be working and it has been committed to master. I hope to be able in a short period of time to package it up and release a new version of the software. Hang on for a bit and stay tuned!

**Comment by XxHansYoloxX** [comment]
dancol90 how is this coming along?

**Comment by dancol90** [comment]
Finally released a new version that uses the new hiding system. Check it out: https://github.com/dancol90/mi-360/releases/tag/v0.6.0
