### ISSUE TITLE
Device hidding does not work even in the new version

### ISSUE THREAD

**Issue by bkt** [dancol90/mi-360#27]
At least in my case. I always get duplicated devices.

Edit:
I tried this one, and it works ok and I dont get duplicated devices (using scp). At least mi.exe works, I havent tried the service because I want the icon on tray.

I havent tried with 2 gamepads, hopefullt it works.

https://github.com/Paperfeed/Xiaomi_gamepad/releases/tag/v1.1

Edit2:
I had to reinstall everything to put scp again and got a couple of bluescreens but I will be happy to test new releases of mi-360 in the future. Currently I am trying to make this thing working (Gopher360). Would be great if you could integrate everything on one single exe.

https://github.com/Tylemagne/Gopher360/pull/153
https://github.com/mike1084/GopherRenewed

Edit3:

After trying several tools on github, the only one that seems to work consistently is the @Paperfeed fork. The original release from @irungentoo works well but exclusive mode sometimes crash and have to restart the program or even the computer.

https://github.com/Paperfeed/Xiaomi_gamepad/releases/tag/v1.1

**Comment by dancol90** [comment]
Hi,

Have you followed the setup instructions correctly? Did you install HidHide and ViGEm drivers from the provided links?

**Comment by bkt** [comment]
Yep, I installed both hidhide and vigem ofc.

Only scp + @paperfeed version worked for me.

I put an autostart task for @paperfeed .exe, and the gamepad connects always as a x360 without user interaction.

**Comment by tawnycat21** [comment]
hei i have same problem here with the new version, but now i used v0.5.2 again and work fine for me and dont get duplicate

**Comment by dancol90** [comment]
Fixed in 2fb16a213390970c0bdfd1b2a64ba266320f02f3!

**Comment by dancol90** [comment]
Released v0.6.1, check it out!
