### ISSUE TITLE
Y Axis not configured correctly

### ISSUE THREAD

**Issue by redline99cs** [dancol90/mi-360#28]
Please kindly recheck your newest version.
The Y Axis is not configured corrrectly with my xiaomi gameupad.
In the previous version it was fine.
Thanks for reviving the project.

**Comment by heeroyuyj** [comment]
same issue here... left stick's up = down, test in many games

**Comment by LEMIR13** [comment]
Same, can't go front

**Comment by dancol90** [comment]
Sorry guys, I'll have a look as soon as possible

**Comment by heeroyuyj** [comment]
well, found an acient mi pad github project (https://github.com/irungentoo/Xiaomi_gamepad), it works without left sticker problem @LEMIR13 @redline99cs

**Comment by Drawork** [comment]
Same error here, I have to mention that version 0.5.2 works perfectly. It seems that only fails when the stick is in its maximum position, while you slide it to there it works perfectly.  (left stick forward)
Thank you for your work 😉

**Comment by dancol90** [comment]
Hi everybody, just a quick update. I might have found a possible cause for this problem. I'm working on a solution. Stay tuned.

**Comment by dancol90** [comment]
Fixed in 9d17cfca272478d877efa07f0a5697d61976a04e!

**Comment by dancol90** [comment]
Released v0.6.1, check it out!
