### ISSUE TITLE
Hiding of Xiaomi controller + object errors

### ISSUE THREAD

**Issue by Benik3** [dancol90/mi-360#3]
Hello there.

First of all, I must thank you, it works really well :)
Now why I'm writing, on the main page is, that this app has ability to "cover" original xiaomi controller from system, so games can't detect it.
In Train (first episode, didn't tested 2 or 3) I still can see two devices - Xiaomi and XInput.
It made me little hard time, because one button worked as 2 controllers spawning second person. Luckily I can delete mapping for the controller, so I was able to solve it while playing.
But I think that it still cause problems in menu, because e.g. B is for select (instead of back) etc.

When I look into device manager, I really don't see the Xiaomi controller, so I don't know, where it got it :/

I tested also e.g. Battle Block Theater and it looks working fine.

Thanks for any idea!

**Comment by Benik3** [comment]
Well I just found, that disabling Network Listing service can help.
I tested it and I really don't see Xiaomi controller in the game anymore and menu is working fine now.
I assume that there is no way how to do it without of disabling the service...

**Comment by Benik3** [comment]
I had to turn the service back to automatic run, otherwise I got lot of errors in system events :/
If there is any other way, it would be great!

EDIT:
At the end I solved the issue, but I'm not sure how.
I updated all Vigem drivers to latest version (1.14.1.0) but I also completely removed and uninstalled any other drivers (scp...) and also removed all old HID and USB devices from Device manager.
After that the hiding of Xiaomi controller works OK even with running network listing service :)

Anyway I still have one more "bug". On every first run of the MI-360 I got error:
_**Mi-360 has stopped working. The cause of the problem is:
object reference not set to an instance of an object**_
But the application run (until I click on OK in the error msg box). On second and more runs it doesn't happen any more.
And when I exit the application I get this error:
_**Mi-360 has stopped working. The cause of the problem is:
Cannot access a disposed object.**_

But everything is working fine :)

**Comment by dancol90** [comment]
Hi,

I solved the errors at startup and shutdown in e29fcfaf599598d8d6dfed29ed131c5cf0476a99. 
Regarding the visibility problem, yeah having ViGEm and SCPToolkit installer together might cause troubles! Glad that now mi-360 works fine for you!
