### ISSUE TITLE
It has been used well, but it suddenly appears gamepad disconnected 

### ISSUE THREAD

**Issue by luxunhua** [dancol90/mi-360#32]
All text of the prompt is "A gamepad has disconnected and is not available anymore".Please tell me what's going on and how to solve it 
 .thank you very much.

**Comment by luxunhua** [comment]
I vaguely remember that I installed irungentoo/Xiaomi by mistake_ After the scp in the gamepad is used, your program will not work properly.（I can only use irungentoo/Xiaomi_ Mi program of gamepad.Then there is a bug in his program. In Elden Ring, the lt key of the handle cannot be used, but it is normal in other games.）So I want to know how to continue using your program.

**Comment by luxunhua** [comment]
So I want to know how to continue using your program. I'm sorry to trouble you

**Comment by dancol90** [comment]
It seems that you are having problems after installing SCPToolkit, right? If that's the case, SCP is not compatible with ViGem (that's meant to be its successor and that mi-360 uses), so you may try with a full uninstallation of SCPToolkit

**Comment by luxunhua** [comment]
> 看来您在安装 SCPToolkit 后遇到了问题，对吧？如果是这种情况，SCP与ViGem不兼容（这是它的继任者，而mi-360使用），所以你可以尝试完全卸载SCPToolkit。

thanks bro
solved the problem with your method
