### ISSUE TITLE
could you update it

### ISSUE THREAD

**Issue by thomasthinhvu** [dancol90/mi-360#4]
hi Dancol90 
on the readme note you wrote
"..... pre-packaged setup
Download the latest version of the setup from the Releases page and run it.""
but where is that page, i can not see that link.
im sorry i just a normal people i can not combine script...  ?? could you link it to me.
thank you

**Comment by dancol90** [comment]
It's at the top of the page, next to commits and branches links. Or you can use this direct link:

https://github.com/dancol90/mi-360/releases

**Comment by thomasthinhvu** [comment]
thank you so much, its work perfectly 👍
