### ISSUE TITLE
Error first run...

### ISSUE THREAD

**Issue by gmpapps** [dancol90/mi-360#5]
Hey there, just want to thank to you for this, its working perfectly.. But i have little issues when first run sometimes show error like this "Mi-360 has stopped working. The cause of the problem is:
object reference not set to an instance of an object"
Can you fix it, and more better if you can make running at startup automatically.. 
Thanks in advance.

**Comment by maciekz** [comment]
Hi :)

I also sometimes experience the error on first run but I've mostly come here to thank you @dancol90 for your great work - this solutions works wonderfully with Xiaomi Gamepad :)

Regards,
Maciejt

**Comment by waelabdrabbo** [comment]
yes i have the same issue also.

**Comment by diegoweb** [comment]
This software is working great.
The only issue that I'm having now is when turn off the controller before closing the app, then I get the same message as OP has reported.
Aside from that, working great. Even better than irungentoo/Xiaomi_gamepad solution.

**Comment by dancol90** [comment]
Hi everybody, thank for the feedbacks.
Sorry for the long wait, I had a fix for this crashes ready for a long time but never had the chance to release them...until now!

Please update to version v0.4.0 and let me know if everything's ok!

**Comment by maciekz** [comment]
I can confirm that after update to v0.4.0 the error on first run is now gone.
