### ISSUE TITLE
announce correct battery percentage via XInput

### ISSUE THREAD

**Issue by NyaomiDEV** [dancol90/mi-360#9]
XInput has an API to show battery status and several applications use it to show the battery status of Xbox 360/One wireless controllers. Since I have mixed controllers (one Xiaomi, two wireless X360 and a wireless XOne) it would be cool to only have my Rainmeter setup displaying the battery status of all the controllers via the XInput API, but the Xiaomi controller always displays 100% battery... Can you fix it?

**Comment by dancol90** [comment]
I think that the driver I'm using, ViGEM, doesn't expose this feature, at least in the current version

**Comment by NyaomiDEV** [comment]
Oh, that's unfortunate...
